import type {
  Creature,
  DailyTask,
  DungeonStage,
  Equipment,
  Friend,
  GachaBanner,
  GuildInfo,
  PvpOpponent,
  Skill,
  UserProfile,
} from "@/types/game";

// Lives here (rather than lib/store.ts) so server-only modules — e.g. lib/db/bigquery.ts,
// deciding how many of an admin account's creatures go into the hub team — can read it
// without pulling zustand/React into a server bundle.
export const HUB_TEAM_SIZE = 7;

function skill(
  id: string,
  name: string,
  description: string,
  type: Skill["type"],
  power: number,
  cooldown: number,
  unlockLevel = 1
): Skill {
  return { id, name, description, type, power, cooldown, unlockLevel };
}

export const STARTER_CREATURES: Creature[] = [
  {
    id: "cr-emberling",
    name: "Emberling",
    element: "Fire",
    rarity: "Rare",
    level: 12,
    exp: 340,
    expToNextLevel: 600,
    stage: 1,
    spriteKey: "emberling",
    baseStats: { hp: 620, atk: 148, def: 76, spd: 104 },
    skills: [
      skill("sk-em-1", "Cinder Claw", "A blazing slash dealing fire damage to one enemy.", "Attack", 140, 0),
      skill("sk-em-2", "Flare Guard", "Raises own DEF for 2 turns.", "Defense", 0, 3, 5),
      skill("sk-em-3", "Ash Cyclone", "Hits all enemies with a spinning ember burst.", "Attack", 95, 4, 10),
      skill("sk-em-4", "Rekindle", "Passively regenerates HP each turn.", "Passive", 0, 0, 15),
    ],
    equipment: {},
  },
  {
    id: "cr-tidalfin",
    name: "Tidalfin",
    element: "Water",
    rarity: "SSR",
    level: 15,
    exp: 120,
    expToNextLevel: 720,
    stage: 2,
    spriteKey: "tidalfin",
    baseStats: { hp: 780, atk: 132, def: 94, spd: 96 },
    skills: [
      skill("sk-ti-1", "Riptide Slash", "A pressurized water strike on one enemy.", "Attack", 132, 0),
      skill("sk-ti-2", "Healing Tide", "Restores HP to the lowest-HP ally.", "Support", 110, 3, 8),
      skill("sk-ti-3", "Whirlpool", "Pulls all enemies in, dealing water damage.", "Attack", 88, 4, 12),
      skill("sk-ti-4", "Deep Focus", "Passively boosts SPD when HP is above 50%.", "Passive", 0, 0, 18),
    ],
    equipment: {},
  },
  {
    id: "cr-gale-sprite",
    name: "Gale Sprite",
    element: "Nature",
    rarity: "Common",
    level: 8,
    exp: 60,
    expToNextLevel: 320,
    stage: 1,
    spriteKey: "gale-sprite",
    baseStats: { hp: 480, atk: 110, def: 62, spd: 132 },
    skills: [
      skill("sk-ga-1", "Vine Whip", "A quick nature strike on one enemy.", "Attack", 105, 0),
      skill("sk-ga-2", "Thorn Veil", "Reduces incoming damage for 2 turns.", "Defense", 0, 3, 5),
      skill("sk-ga-3", "Bloom Burst", "Nature damage to all enemies with a chance to slow.", "Attack", 80, 4, 10),
      skill("sk-ga-4", "Photosynthesis", "Passively restores small HP each turn in daylight.", "Passive", 0, 0, 12),
    ],
    equipment: {},
  },
  {
    id: "cr-voltling",
    name: "Voltling",
    element: "Electric",
    rarity: "Rare",
    level: 10,
    exp: 210,
    expToNextLevel: 480,
    stage: 1,
    spriteKey: "voltling",
    spriteFolder: "/assets/creatures/voltling/idle",
    baseStats: { hp: 540, atk: 138, def: 68, spd: 140 },
    skills: [
      skill("sk-vo-1", "Spark Bite", "A quick electric nip on one enemy.", "Attack", 120, 0),
      skill("sk-vo-2", "Static Charge", "Raises own SPD for 2 turns.", "Defense", 0, 3, 5),
      skill("sk-vo-3", "Thunder Dash", "Electric damage to all enemies with a chance to stun.", "Attack", 92, 4, 10),
      skill("sk-vo-4", "Capacitor Coils", "Passively charges up, boosting the next skill's power.", "Passive", 0, 0, 14),
    ],
    equipment: {},
  },
  {
    id: "cr-firebit",
    name: "Firebit",
    element: "Fire",
    rarity: "Rare",
    level: 9,
    exp: 150,
    expToNextLevel: 420,
    stage: 1,
    spriteKey: "firebit",
    spriteFolder: "/assets/creatures/firebit/idle",
    baseStats: { hp: 560, atk: 144, def: 70, spd: 118 },
    skills: [
      skill("sk-fb-1", "Ember Nip", "A quick fiery bite on one enemy.", "Attack", 128, 0),
      skill("sk-fb-2", "Sun Cloak", "Raises own DEF for 2 turns.", "Defense", 0, 3, 5),
      skill("sk-fb-3", "Wildfire Romp", "Fire damage to all enemies with a chance to burn.", "Attack", 90, 4, 10),
      skill("sk-fb-4", "Kindle Spirit", "Passively regenerates a small amount of HP each turn.", "Passive", 0, 0, 13),
    ],
    equipment: {},
  },
  {
    id: "cr-dragoon",
    name: "Dragoon",
    element: "Nature",
    rarity: "SSR",
    level: 11,
    exp: 260,
    expToNextLevel: 540,
    stage: 1,
    spriteKey: "dragoon",
    spriteFolder: "/assets/creatures/dragoon/idle",
    baseStats: { hp: 610, atk: 142, def: 88, spd: 108 },
    skills: [
      skill("sk-dr-1", "Tail Lash", "A sweeping tail strike on one enemy.", "Attack", 134, 0),
      skill("sk-dr-2", "Scale Harden", "Raises own DEF for 2 turns.", "Defense", 0, 3, 5),
      skill("sk-dr-3", "Verdant Roar", "Nature damage to all enemies with a chance to slow.", "Attack", 96, 4, 10),
      skill("sk-dr-4", "Regenerative Hide", "Passively restores HP each turn based on max HP.", "Passive", 0, 0, 16),
    ],
    equipment: {},
  },
  {
    id: "cr-crimson-guardian",
    name: "CrimsonGuardian",
    element: "Fire",
    rarity: "Mythic",
    level: 30,
    exp: 800,
    expToNextLevel: 2000,
    stage: 3,
    spriteKey: "crimsonguardian",
    spriteFolder: "/assets/creatures/crimsonguardian/idle",
    baseStats: { hp: 980, atk: 205, def: 138, spd: 92 },
    skills: [
      skill("sk-cg-1", "Blazing Judgment", "A sword strike wreathed in crimson flame on one enemy.", "Attack", 172, 0),
      skill("sk-cg-2", "Aegis of Embers", "Raises own DEF sharply for 2 turns with the ceremonial shield.", "Defense", 0, 3, 5),
      skill("sk-cg-3", "Crimson Cataclysm", "An overwhelming flame judgment on all enemies.", "Attack", 138, 5, 15),
      skill("sk-cg-4", "Guardian's Resolve", "Passively reduces damage taken when HP falls below 30%.", "Passive", 0, 0, 20),
    ],
    equipment: {},
  },
  {
    id: "cr-silver-dragon",
    name: "SilverDragon",
    element: "Light",
    rarity: "Mythic",
    level: 32,
    exp: 950,
    expToNextLevel: 2200,
    stage: 3,
    spriteKey: "silverdragon",
    spriteFolder: "/assets/creatures/silverdragon/idle",
    baseStats: { hp: 1040, atk: 198, def: 128, spd: 108 },
    skills: [
      skill("sk-sd-1", "Radiant Fang", "A blessed bite crackling with electric light on one enemy.", "Attack", 168, 0),
      skill("sk-sd-2", "Sacred Scales", "Raises own DEF and SPD for 2 turns.", "Defense", 0, 3, 5),
      skill("sk-sd-3", "Astral Nova", "A burst of sacred light damages all enemies with a chance to blind.", "Attack", 132, 5, 15),
      skill("sk-sd-4", "Celestial Ward", "Passively shields the lowest-HP ally each turn.", "Passive", 0, 0, 20),
    ],
    equipment: {},
  },
  {
    id: "cr-venomshade",
    name: "Venomshade",
    element: "Dark",
    rarity: "Rare",
    level: 10,
    exp: 180,
    expToNextLevel: 460,
    stage: 1,
    spriteKey: "bluelf",
    spriteFolder: "/assets/creatures/bluelf/idle",
    baseStats: { hp: 560, atk: 150, def: 64, spd: 128 },
    skills: [
      skill("sk-ve-1", "Toxin Fang", "A poisoned dagger strike on one enemy.", "Attack", 136, 0),
      skill("sk-ve-2", "Shadow Veil", "Raises own evasion for 2 turns.", "Defense", 0, 3, 5),
      skill("sk-ve-3", "Venom Flurry", "A flurry of blades hitting all enemies with a chance to poison.", "Attack", 92, 4, 10),
      skill("sk-ve-4", "Creeping Poison", "Passively deals damage over time to a poisoned enemy.", "Passive", 0, 0, 14),
    ],
    equipment: {},
  },
  {
    id: "cr-tidewarden",
    name: "Tidewarden",
    element: "Water",
    rarity: "Rare",
    level: 9,
    exp: 140,
    expToNextLevel: 400,
    stage: 1,
    spriteKey: "orca",
    spriteFolder: "/assets/creatures/orca/idle",
    baseStats: { hp: 600, atk: 126, def: 82, spd: 110 },
    skills: [
      skill("sk-tw-1", "Tidal Slam", "A crushing wave-borne strike on one enemy.", "Attack", 122, 0),
      skill("sk-tw-2", "Ancestral Ward", "Raises own DEF for 2 turns, blessed by totem spirits.", "Defense", 0, 3, 5),
      skill("sk-tw-3", "Riptide Chant", "Water damage to all enemies with a chance to slow.", "Attack", 86, 4, 10),
      skill("sk-tw-4", "Spirit Current", "Passively restores a small amount of HP each turn.", "Passive", 0, 0, 13),
    ],
    equipment: {},
  },
  {
    id: "cr-emberfiend",
    name: "Emberfiend",
    element: "Dark",
    rarity: "SSR",
    level: 13,
    exp: 300,
    expToNextLevel: 620,
    stage: 2,
    spriteKey: "crimsonwarrior",
    spriteFolder: "/assets/creatures/crimsonwarrior/idle",
    baseStats: { hp: 680, atk: 168, def: 98, spd: 100 },
    skills: [
      skill("sk-ef-1", "Magma Cleave", "A molten greatsword strike on one enemy.", "Attack", 158, 0),
      skill("sk-ef-2", "Infernal Bulwark", "Raises own DEF sharply for 2 turns.", "Defense", 0, 3, 5),
      skill("sk-ef-3", "Ashen Wingstorm", "A sweep of smoldering wings damaging all enemies.", "Attack", 112, 4, 11),
      skill("sk-ef-4", "Undying Wrath", "Passively raises ATK when HP falls below 40%.", "Passive", 0, 0, 16),
    ],
    equipment: {},
  },
  {
    id: "cr-thundracoil",
    name: "Thundracoil",
    element: "Electric",
    rarity: "SSR",
    level: 14,
    exp: 340,
    expToNextLevel: 660,
    stage: 2,
    spriteKey: "easterndragon",
    spriteFolder: "/assets/creatures/easterndragon/idle",
    baseStats: { hp: 640, atk: 158, def: 86, spd: 132 },
    skills: [
      skill("sk-th-1", "Storm Fang", "A lightning-wreathed bite on one enemy.", "Attack", 150, 0),
      skill("sk-th-2", "Static Scales", "Raises own SPD for 2 turns.", "Defense", 0, 3, 5),
      skill("sk-th-3", "Tempest Roar", "A crashing storm damaging all enemies with a chance to stun.", "Attack", 108, 4, 12),
      skill("sk-th-4", "Galvanic Core", "Passively charges up, boosting the next skill's power.", "Passive", 0, 0, 17),
    ],
    equipment: {},
  },
  {
    id: "cr-starweaver",
    name: "Starweaver",
    element: "Light",
    rarity: "SSR",
    level: 12,
    exp: 260,
    expToNextLevel: 600,
    stage: 2,
    spriteKey: "magicelf",
    spriteFolder: "/assets/creatures/magicelf/idle",
    baseStats: { hp: 620, atk: 140, def: 88, spd: 118 },
    skills: [
      skill("sk-sw-1", "Starlight Lance", "A bolt of celestial energy on one enemy.", "Attack", 132, 0),
      skill("sk-sw-2", "Astral Shield", "Shields the lowest-HP ally for 2 turns.", "Support", 0, 3, 5),
      skill("sk-sw-3", "Nova Cascade", "A burst of starlight damaging all enemies.", "Attack", 96, 4, 11),
      skill("sk-sw-4", "Guiding Light", "Passively restores HP to the lowest-HP ally each turn.", "Passive", 0, 0, 15),
    ],
    equipment: {},
  },
];

// The 3 creatures offered during registration. All stage 1, one per starter element.
export const STARTER_CHOICE_IDS = ["cr-emberling", "cr-gale-sprite", "cr-voltling"] as const;
export type StarterChoiceId = (typeof STARTER_CHOICE_IDS)[number];

export const STARTER_EQUIPMENT: Equipment[] = [
  {
    id: "eq-ember-blade",
    name: "Ember Blade",
    slot: "Weapon",
    rarity: "Rare",
    enhancementLevel: 3,
    baseStats: { atk: 42 },
    setName: "Blazing Fury",
  },
  {
    id: "eq-tidal-crown",
    name: "Tidal Crown",
    slot: "Helmet",
    rarity: "SSR",
    enhancementLevel: 5,
    baseStats: { hp: 120, def: 18 },
    setName: "Abyssal Guard",
  },
  {
    id: "eq-gale-wings",
    name: "Gale Wings",
    slot: "Wings",
    rarity: "Rare",
    enhancementLevel: 2,
    baseStats: { spd: 24 },
    setName: "Windrunner",
  },
  {
    id: "eq-ashen-aura",
    name: "Ashen Aura",
    slot: "Aura",
    rarity: "Mythic",
    enhancementLevel: 0,
    baseStats: { atk: 30, spd: 12 },
    setName: "Blazing Fury",
  },
  {
    id: "eq-scale-plate",
    name: "Scale Plate",
    slot: "Armor",
    rarity: "Common",
    enhancementLevel: 1,
    baseStats: { hp: 90, def: 22 },
  },
];

export const DEFAULT_PROFILE: UserProfile = {
  id: "player-1",
  name: "Summoner",
  title: "Novice Tamer",
  level: 7,
  exp: 240,
  expToNextLevel: 500,
  avatarKey: "avatar-default",
  isAdmin: false,
};

export const DEFAULT_DAILY_TASKS: DailyTask[] = [
  { id: "task-login", description: "Log in to the city hub", progress: 1, target: 1, rewardGold: 500, claimed: false },
  { id: "task-dungeon", description: "Clear 3 dungeon waves", progress: 1, target: 3, rewardGems: 30, claimed: false },
  { id: "task-gacha", description: "Perform 1 summon", progress: 0, target: 1, rewardGold: 1000, claimed: false },
  { id: "task-enhance", description: "Enhance a piece of gear", progress: 0, target: 1, rewardGems: 20, claimed: false },
];

export const GACHA_BANNERS: GachaBanner[] = [
  {
    id: "banner-corazon-de-roca",
    name: "Corazón de Roca",
    tagline: "El latido del mundo. Inquebrantable.",
    type: "Creature",
    bannerImage: "/assets/banners/banner_demo_1.png",
    featuredIds: ["cr-dragoon"],
    singlePullCost: 100,
    multiPullCost: 650,
    multiPullCount: 7,
  },
  {
    id: "banner-caballero-real-dragon",
    name: "Caballero Real",
    tagline: "La justicia protege al mundo.",
    type: "Creature",
    bannerImage: "/assets/banners/banner_knight_real_2.png",
    featuredIds: ["cr-voltling"],
    singlePullCost: 100,
    multiPullCost: 650,
    multiPullCount: 7,
  },
  {
    id: "banner-caballero-real-knight",
    name: "Caballero Real",
    tagline: "La justicia es mi espada. Mi escudo, mi honor.",
    type: "Creature",
    bannerImage: "/assets/banners/banner_royal_knight_1.png",
    featuredIds: ["cr-firebit"],
    singlePullCost: 100,
    multiPullCost: 650,
    multiPullCount: 7,
  },
];

export const PVP_LEADERBOARD: PvpOpponent[] = [
  { id: "pvp-1", name: "Kael the Ashen", tier: "Grandmaster", rank: 1, power: 18420, defenseTeamCreatureIds: ["cr-tidalfin", "cr-emberling", "cr-gale-sprite"] },
  { id: "pvp-2", name: "Lyra Nightshade", tier: "Diamond", rank: 2, power: 16210, defenseTeamCreatureIds: ["cr-tidalfin", "cr-emberling"] },
  { id: "pvp-3", name: "Doran Ironfist", tier: "Platinum", rank: 3, power: 14980, defenseTeamCreatureIds: ["cr-emberling", "cr-gale-sprite"] },
  { id: "pvp-4", name: "Mira Frostwing", tier: "Gold", rank: 4, power: 12340, defenseTeamCreatureIds: ["cr-gale-sprite"] },
  { id: "pvp-5", name: "Bram Stonehide", tier: "Silver", rank: 5, power: 9870, defenseTeamCreatureIds: ["cr-emberling"] },
];

const STAGE_NAMES = [
  "Whispering Grove", "Ember Foothills", "Tidewater Shoals", "Sunken Ruins",
  "Ashfall Canyon", "Glimmering Caverns", "Thornwood Depths", "Frostpeak Pass",
  "Molten Bastion", "Stormlit Shrine", "Duskveil Marsh", "Obsidian Spire",
  "Verdant Labyrinth", "Crimson Aqueduct", "Hollow Bellfort", "Wraithlight Hollow",
  "Ironclad Foundry", "Sable Undercroft", "Gale Citadel", "Dragon's Reprieve",
];

const HIGHEST_STAGE_CLEARED = 0;

export const DUNGEON_STAGES: DungeonStage[] = STAGE_NAMES.map((name, i) => {
  const stageNumber = i + 1;
  const difficulty = stageNumber <= 8 ? "Normal" : stageNumber <= 16 ? "Hard" : "Nightmare";
  const world = Math.floor((stageNumber - 1) / 8) + 1;
  const worldStageNumber = ((stageNumber - 1) % 8) + 1;
  return {
    id: `dg-stage-${stageNumber}`,
    stageNumber,
    world,
    worldStageNumber,
    name,
    difficulty,
    staminaCost: 6 + Math.floor(stageNumber / 3),
    recommendedPower: 800 + stageNumber * 420,
    rewardGold: 300 + stageNumber * 180,
    rewardExp: 80 + stageNumber * 40,
    equipmentDropChance: Math.min(45, 10 + stageNumber * 2),
    isLocked: stageNumber > HIGHEST_STAGE_CLEARED + 1,
    isCleared: stageNumber <= HIGHEST_STAGE_CLEARED,
  };
});

export const MOCK_FRIENDS: Friend[] = [
  { id: "fr-1", name: "Astrid Vale", level: 34, status: "Online", lastActive: "now" },
  { id: "fr-2", name: "Renji Okami", level: 41, status: "In Battle", lastActive: "now" },
  { id: "fr-3", name: "Cass Whitlock", level: 19, status: "Offline", lastActive: "3h ago" },
  { id: "fr-4", name: "Nova Sundstrom", level: 27, status: "Online", lastActive: "now" },
  { id: "fr-5", name: "Emrys Kade", level: 52, status: "Offline", lastActive: "1d ago" },
];

export const MOCK_GUILD: GuildInfo = {
  id: "guild-emberwatch",
  name: "Emberwatch Vanguard",
  level: 12,
  memberCount: 5,
  memberCap: 30,
  description: "A friendly guild focused on dungeon co-op and weekly guild raids. Casual pace, active chat.",
  members: [
    { id: "gm-1", name: "Summoner", role: "Leader", level: 7, weeklyContribution: 4200 },
    { id: "gm-2", name: "Astrid Vale", role: "Officer", level: 34, weeklyContribution: 8900 },
    { id: "gm-3", name: "Renji Okami", role: "Officer", level: 41, weeklyContribution: 7600 },
    { id: "gm-4", name: "Cass Whitlock", role: "Member", level: 19, weeklyContribution: 2100 },
    { id: "gm-5", name: "Nova Sundstrom", role: "Member", level: 27, weeklyContribution: 5400 },
  ],
};
